raw = "data/raw"
processed = "data/processed"
input = "_chat.txt"
current = "whatsapp-20250910-002822-maap-cleaned.parq"
current_1 = "whatsapp-20250910-004727-golf-cleaned.parq"
current_2 = "whatsapp-20250910-012654-voorganger-golf-cleaned.parq"
inputpath = "whatsapp-20250910-001356-maap.csv"
datetime_format = "%d-%m-%Y, %H:%M:%S"
drop_authors =[]